export default {
	FILL_MACHINE_WITH_PRODUCTS: 'FILL_MACHINE_WITH_PRODUCTS',
	FILL_MACHINE_WITH_PRODUCTS_OK: 'FILL_MACHINE_WITH_PRODUCTS_OK',
	FILL_MACHINE_WITH_PRODUCTS_FAIL: 'FILL_MACHINE_WITH_PRODUCTS_FAIL'
};