export default {
	FILL_MACHINE_WITH_PRODUCTS: 'FILL_MACHINE_WITH_PRODUCTS',
	FILL_MACHINE_WITH_PRODUCTS_OK: 'FILL_MACHINE_WITH_PRODUCTS_OK',
	FILL_MACHINE_WITH_PRODUCTS_FAIL: 'FILL_MACHINE_WITH_PRODUCTS_FAIL',

	SET_PRODUCT_FOR_SALE: 'SET_PRODUCT_FOR_SALE',
	CHECK_PURCHASE_ABILITY: 'CHECK_PURCHASE_ABILITY',
	EJECT_PURCHASING_MACHINE_PRODUCTS: 'EJECT_PURCHASING_MACHINE_PRODUCTS'
};