export default {
	GIVE_HUMAN_SOME_CASH: 'GIVE_HUMAN_SOME_CASH',
	GIVE_HUMAN_SOME_CASH_OK: 'GIVE_HUMAN_SOME_CASH_OK',
	GIVE_HUMAN_SOME_CASH_FAIL: 'GIVE_HUMAN_SOME_CASH_FAIL',

	PURCHASE_PRODUCTS: 'PURCHASE_PRODUCTS'
};